CREATE TABLE Colour
(
	ColourID		INT IDENTITY(1, 1) NOT NULL CONSTRAINT PK_ColourID PRIMARY KEY,
	ColourName		NVARCHAR(25) NOT NULL
);

CREATE TABLE RangeType
(
	RangeID			INT IDENTITY(1, 1) NOT NULL CONSTRAINT PK_RangeID PRIMARY KEY,
	RangeName		NVARCHAR(25) NOT NULL
)

CREATE TABLE BagType
(
	BagTypeID		INT IDENTITY(1, 1) NOT NULL CONSTRAINT PK_BagTypeID PRIMARY KEY,
	BagType			NVARCHAR(25) NOT NULL
)

CREATE TABLE ProductDetails
(
	ProductCode		INT IDENTITY(1, 1) NOT NULL CONSTRAINT PK_ProductCode PRIMARY KEY,
	ProductName		NVARCHAR(100) NOT NULL,
	[Description]	NVARCHAR(255),
	ColourID		INT CONSTRAINT FK_ColourID FOREIGN KEY REFERENCES Colour(ColourID),
	ProductImage	NVARCHAR(50),
	Price			DECIMAL(5,2) NOT NULL,
	RangeID			INT CONSTRAINT FK_RangeID FOREIGN KEY REFERENCES RangeType(RangeID),
	BagTypeID		INT CONSTRAINT FK_BagTypeID FOREIGN KEY REFERENCES BagType(BagTypeID)
)

CREATE TABLE PaymentType
(
	PaymentTypeID	INT IDENTITY(1, 1) NOT NULL CONSTRAINT PK_PaymentTypeID PRIMARY KEY,
	CustomerID		NVARCHAR(450) NOT NULL,
	PaymentMethod	NVARCHAR(50) NOT NULL,
	NameOnCard		NVARCHAR(50) NOT NULL,
	CardNumber		INT NOT NULL,
	ExpirationDate	NVARCHAR(8) NOT NULL
)

CREATE TABLE OrderDetails
(
	OrderID			INT IDENTITY(1, 1) NOT NULL CONSTRAINT PK_OrderID PRIMARY KEY,
	CustomerID		NVARCHAR(450) NOT NULL,
	PaymentTypeID	INT CONSTRAINT FK_PaymentTypeID FOREIGN KEY REFERENCES PaymentType(PaymentTypeID),
	DateOrdered		DATETIME2 NOT NULL,
	DatePurchased	DATETIME2 NOT NULL,
)

CREATE TABLE ProductOrderDetails
(
	OrderID			INT NOT NULL CONSTRAINT FK_OrderID FOREIGN KEY REFERENCES OrderDetails(OrderID),
	ProductID		INT NOT NULL CONSTRAINT FK_ProductID FOREIGN KEY REFERENCES ProductDetails(ProductCode),
	Quantity		INT NOT NULL,
	UnitPrice		Decimal NOT NULL,
	TotalPrice		AS (Quantity * UnitPrice),
	CONSTRAINT PK_ProductOrderDetails PRIMARY KEY (OrderID, ProductID)
)

CREATE TABLE Addresses
(
	AddressID		INT IDENTITY(1, 1) NOT NULL CONSTRAINT PK_AddressID PRIMARY KEY,
	Line1			NVARCHAR(100) NOT NULL,
	Line2			NVARCHAR(100),
	City			NVARCHAR(50) NOT NULL,
	Postcode		NVARCHAR(8) NOT NULL,
	Country			NVARCHAR(50) NOT NULL
)

CREATE TABLE CustomerAddresses
(
	AddressID		INT NOT NULL CONSTRAINT FK_AddressID FOREIGN KEY REFERENCES Addresses(AddressID),
	CustomerID		NVARCHAR(450) NOT NULL
	CONSTRAINT PK_CustomerAddresses PRIMARY KEY (AddressID, CustomerID)
)